image: elixir:latest

# List of stages for jobs, and their order of execution
stages:
  - test

variables:
  MIX_ENV: "test"

before_script:
  - mix local.rebar --force
  - mix local.hex --force
  - mix deps.get

test:
  stage: test
  script:
    - mix test
